# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: bazzite-gnome-dx
# description will be included in the image's metadata
description: Bazzite - Custom image to add development tools and add some customizations

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/bazzite-gnome
image-version: latest

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: rpm-ostree
    repos:
      - https://download.docker.com/linux/fedora/docker-ce.repo
      - https://copr.fedorainfracloud.org/coprs/architektapx/zen-browser/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo
      - https://packages.microsoft.com/yumrepos/vscode
      - https://downloads.1password.com/linux/rpm/stable/x86_64
    keys:
      - https://download.docker.com/linux/fedora/gpg
      - https://packages.microsoft.com/keys/microsoft.asc
      - https://downloads.1password.com/linux/keys/1password.asc
    install:
      - docker-ce
      - docker-ce-cli
      - docker-buildx-plugin
      - docker-compose-plugin
      - code
      - zen-browser
      - papirus-icon-theme

  - type: default-flatpaks
    notify: false
    system:
      install:
        - dev.vencord.Vesktop
        - com.google.Chrome
        - rest.insomnia.Insomnia
        - com.spotify.Client
        - com.heroicgameslauncher.hgl
      remove:
        - org.mozilla.firefox

  - type: fonts
    fonts:
      nerd-fonts:
        - FiraCode
        - JetBrainsMono
      google-fonts:
        - Roboto
        - Open Sans

  - type: signing # this sets up the proper policy & signing files for signed images to work fully

