# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: bazzite-dx-gnome
# description will be included in the image's metadata
description: Bazzite - Custom image to add development tools and add some customizations

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/bazzite-gnome
image-version: latest

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: rpm-ostree
    repos:
      - https://copr.fedorainfracloud.org/coprs/sneexy/zen-browser/repo/fedora-%OS_VERSION%/sneexy-zen-browser-fedora-%OS_VERSION%.repo
    install:
      - papirus-icon-theme
      - openrgb
      - coolercontrol
      - zen-browser

  - type: default-flatpaks
    notify: false
    system:
      install:
        - dev.vencord.Vesktop
        - com.google.Chrome
        - rest.insomnia.Insomnia
        - com.spotify.Client
        - com.heroicgameslauncher.hgl
      remove:
        - org.mozilla.firefox

  - type: systemd
    system:
      enabled:
        - coolercontrol.service

  - type: fonts
    fonts:
      nerd-fonts:
        - FiraCode
        - JetBrainsMono

  - type: signing # this sets up the proper policy & signing files for signed images to work fully

